// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A GenAI-assisted profile bio generator.
 *
 * - generateProfileBio - A function that generates a profile bio using GenAI.
 * - GenerateProfileBioInput - The input type for the generateProfileBio function.
 * - GenerateProfileBioOutput - The return type for the generateProfileBio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProfileBioInputSchema = z.object({
  role: z.string().describe('The role of the user (e.g., artist, creator, business).'),
  skills: z.string().describe('A comma-separated list of skills the user possesses.'),
  interests: z.string().describe('A comma-separated list of the user\'s interests.'),
  style: z
    .enum(['professional', 'casual', 'humorous', 'inspirational'])
    .describe('The desired style of the bio.'),
});
export type GenerateProfileBioInput = z.infer<typeof GenerateProfileBioInputSchema>;

const GenerateProfileBioOutputSchema = z.object({
  bio: z.string().describe('The generated profile bio.'),
});
export type GenerateProfileBioOutput = z.infer<typeof GenerateProfileBioOutputSchema>;

export async function generateProfileBio(input: GenerateProfileBioInput): Promise<GenerateProfileBioOutput> {
  return generateProfileBioFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProfileBioPrompt',
  input: {schema: GenerateProfileBioInputSchema},
  output: {schema: GenerateProfileBioOutputSchema},
  prompt: `You are a profile bio creation assistant. You will generate a short profile bio for a new user, based on their background, skills, and desired style.

Role: {{{role}}}
Skills: {{{skills}}}
Interests: {{{interests}}}
Style: {{{style}}}

Write a compelling profile bio in the requested style, incorporating the user's role, skills, and interests.

Output the bio in a single paragraph.  Do not include a title or other extraneous information.`, // eslint-disable-line max-len
});

const generateProfileBioFlow = ai.defineFlow(
  {
    name: 'generateProfileBioFlow',
    inputSchema: GenerateProfileBioInputSchema,
    outputSchema: GenerateProfileBioOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
