import type { User, Video, Bookmark, Tip, GossipPost, GossipComment, GossipRating, GossipUserFollows, GossipServiceAd } from './types';

export const users: User[] = [
  {
    id: '1',
    userId: '1',
    walletAddress: 'artist_wallet_1',
    username: 'LunaVibe',
    role: 'artist',
    bio: 'Singer-songwriter weaving dreams into melodies. Exploring the space between lo-fi beats and soulful vocals. Join my journey.',
    profilePhotoUrl: 'https://picsum.photos/seed/101/200/200',
    bannerPhotoUrl: 'https://picsum.photos/seed/201/1200/400',
    location: 'Electric City',
    talentCategory: 'music',
    talentSubcategories: ['singer', 'songwriter'],
    socialLinks: { youtube: 'lunavibe', instagram: 'lunavibe', twitter: 'lunavibe' },
    rankingScore: 1250,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },
  {
    id: '2',
    userId: '2',
    walletAddress: 'artist_wallet_2',
    username: 'LeoReigns',
    role: 'artist',
    bio: 'Character actor bringing stories to life. Classically trained, but with a modern edge. Seeking roles that challenge and inspire.',
    profilePhotoUrl: 'https://picsum.photos/seed/103/200/200',
    bannerPhotoUrl: 'https://picsum.photos/seed/203/1200/400',
    location: 'Stagecraft Town',
    talentCategory: 'acting',
    talentSubcategories: ['actor_film_tv', 'theatre'],
    socialLinks: { twitter: 'leoreigns' },
    rankingScore: 980,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: '3',
    userId: '3',
    walletAddress: 'artist_wallet_3',
    username: 'Pixelated',
    role: 'artist',
    bio: 'Digital artist & creator painting with pixels and light. My canvas is the screen, my inspiration is the universe. NFT collections available.',
    profilePhotoUrl: 'https://picsum.photos/seed/102/200/200',
    bannerPhotoUrl: 'https://picsum.photos/seed/202/1200/400',
    location: 'The Grid',
    talentCategory: 'creator',
    talentSubcategories: ['digital_art'],
    socialLinks: { instagram: 'pixelated' },
    rankingScore: 1500,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: '4',
    userId: '4',
    walletAddress: 'business_wallet_1',
    username: 'StarlightEnt',
    role: 'business',
    bio: 'Starlight Entertainment: We find the stars of tomorrow. A full-service production house and talent agency looking for the next big thing.',
    profilePhotoUrl: 'https://picsum.photos/seed/104/200/200',
    bannerPhotoUrl: 'https://picsum.photos/seed/204/1200/400',
    location: 'Metropolis',
    socialLinks: { website: 'starlight.ent' },
    rankingScore: 0,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: '5',
    userId: '5',
    walletAddress: 'fan_wallet_1',
    username: 'MusicLover99',
    role: 'fan',
    bio: 'Just here for the vibes and to discover amazing new artists!',
    rankingScore: 0,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  }
];

export const videos: Video[] = [
  {
    id: 'v1',
    videoId: 'v1',
    artistId: '1',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    rawVideoInput: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Check out my new original song "Cosmic Dust"!',
    category: 'music',
    topCount: 150,
    flopCount: 5,
    views: 2500,
    bookCount: 2,
    adoptCount: 1,
    rankingScore: 145,
    bookmarks: 20,
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
  },
  {
    id: 'v2',
    videoId: 'v2',
    artistId: '2',
    videoUrl: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    rawVideoInput: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    description: 'My dramatic monologue from "A Midsummer Night\'s Dream". Hope you like it!',
    category: 'acting',
    topCount: 88,
    flopCount: 12,
    views: 1200,
    bookCount: 0,
    adoptCount: 0,
    rankingScore: 76,
    bookmarks: 10,
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: 'v3',
    videoId: 'v3',
    artistId: '3',
    videoUrl: 'https://www.youtube.com/shorts/3h_nB0sR_RI',
    rawVideoInput: 'https://www.youtube.com/shorts/3h_nB0sR_RI',
    description: 'Speedpaint of my latest digital artwork "Neon City".',
    category: 'creator',
    topCount: 300,
    flopCount: 2,
    views: 5000,
    bookCount: 5,
    adoptCount: 3,
    rankingScore: 298,
    bookmarks: 50,
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: 'v4',
    videoId: 'v4',
    artistId: '1',
    videoUrl: 'https://www.youtube.com/shorts/FT3s2PmctnU',
    rawVideoInput: 'https://www.youtube.com/shorts/FT3s2PmctnU',
    description: 'Acoustic cover of a classic. Let me know what you think!',
    category: 'music',
    topCount: 210,
    flopCount: 8,
    views: 3500,
    bookCount: 1,
    adoptCount: 0,
    rankingScore: 202,
    bookmarks: 35,
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  }
];

export const bookmarks: Bookmark[] = [];
export const tips: Tip[] = [];

export const gossipPosts: GossipPost[] = [
    {
      id: 'gp1',
      authorWallet: 'artist_wallet_1',
      content: 'Just dropped a new track! Feeling super excited about this one. Go check it out on my profile!',
      category: 'announcement',
      createdAt: Date.now() - 1000 * 60 * 30,
      commentsCount: 2,
    },
    {
      id: 'gp2',
      authorWallet: 'artist_wallet_2',
      content: 'Just wrapped up an amazing audition. Fingers crossed! 🤞 #actorlife',
      imageUrl: 'https://picsum.photos/seed/audition/800/400',
      category: 'achievement',
      createdAt: Date.now() - 1000 * 60 * 60 * 2,
      commentsCount: 1,
    },
    {
      id: 'gp3',
      authorWallet: 'fan_wallet_1',
      content: 'Anyone have recommendations for up-and-coming digital artists? Looking for cool new NFTs.',
      category: 'question',
      createdAt: Date.now() - 1000 * 60 * 60 * 5,
      commentsCount: 1,
    },
    {
      id: 'gp4',
      authorWallet: 'artist_wallet_3',
      content: 'My latest art piece "Cybernetic Dreams" is now available as a limited edition print in the marketplace!',
      imageUrl: 'https://picsum.photos/seed/cybernetic/800/400',
      category: 'general',
      createdAt: Date.now() - 1000 * 60 * 60 * 24,
      commentsCount: 0,
    },
];

export const gossipComments: GossipComment[] = [
    { id: 'gc1', postId: 'gp1', authorWallet: 'fan_wallet_1', content: '🔥🔥🔥 This is a banger!', createdAt: Date.now() - 1000 * 60 * 25 },
    { id: 'gc2', postId: 'gp1', authorWallet: 'artist_wallet_2', content: 'Sounds great, Luna!', createdAt: Date.now() - 1000 * 60 * 20 },
    { id: 'gc3', postId: 'gp2', authorWallet: 'fan_wallet_1', content: 'You got this!!', createdAt: Date.now() - 1000 * 60 * 50 },
    { id: 'gc4', postId: 'gp3', authorWallet: 'artist_wallet_3', content: 'You should check out my work! @Pixelated', createdAt: Date.now() - 1000 * 60 * 60 * 4 },
];

export const gossipRatings: GossipRating[] = [
    { id: 'gr1', postId: 'gp1', raterWallet: 'fan_wallet_1', score: 5 },
    { id: 'gr2', postId: 'gp1', raterWallet: 'artist_wallet_2', score: 4 },
    { id: 'gr3', postId: 'gp2', raterWallet: 'fan_wallet_1', score: 5 },
    { id: 'gr4', postId: 'gp3', raterWallet: 'artist_wallet_3', score: 4 },
];

export const gossipFollows: GossipUserFollows[] = [
    { id: 'gf1', followerWallet: 'fan_wallet_1', followingWallet: 'artist_wallet_1' },
    { id: 'gf2', followerWallet: 'fan_wallet_1', followingWallet: 'artist_wallet_3' },
    { id: 'gf3', followerWallet: 'artist_wallet_2', followingWallet: 'artist_wallet_1' },
];

export const serviceAds: GossipServiceAd[] = [
    {
        id: 'ad1',
        title: 'Pro Mix & Master Your Track',
        description: 'Industry-standard mixing and mastering services for artists. Get that radio-ready sound. Fast turnaround, affordable rates.',
        contactInfo: 'mixmasterpro@email.com',
        imageUrl: 'https://picsum.photos/seed/mixing/800/200',
        workLinks: 'https://example.com/portfolio'
    },
    {
        id: 'ad2',
        title: 'Custom Actor Headshots',
        description: 'Professional headshots that get you noticed. Studio and outdoor sessions available. Look your best for casting directors.',
        contactInfo: 'headshots@photo.com',
        imageUrl: 'https://picsum.photos/seed/headshot/800/200',
    }
];
