import type { User, Video } from './types';

export const users: User[] = [
  {
    id: '1',
    userId: '1',
    walletAddress: 'artist_wallet_1',
    username: 'LunaVibe',
    role: 'artist',
    bio: 'Singer-songwriter weaving dreams into melodies. Exploring the space between lo-fi beats and soulful vocals. Join my journey.',
    profilePhotoUrl: 'https://picsum.photos/seed/101/200/200',
    bannerPhotoUrl: 'https://picsum.photos/seed/201/1200/400',
    location: 'Electric City',
    talentCategory: 'music',
    talentSubcategories: ['singer', 'songwriter'],
    socialLinks: { youtube: 'lunavibe', instagram: 'lunavibe', twitter: 'lunavibe' },
    rankingScore: 1250,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },
  {
    id: '2',
    userId: '2',
    walletAddress: 'artist_wallet_2',
    username: 'LeoReigns',
    role: 'artist',
    bio: 'Character actor bringing stories to life. Classically trained, but with a modern edge. Seeking roles that challenge and inspire.',
    profilePhotoUrl: 'https://picsum.photos/seed/103/200/200',
    bannerPhotoUrl: 'https://picsum.photos/seed/203/1200/400',
    location: 'Stagecraft Town',
    talentCategory: 'acting',
    talentSubcategories: ['actor_film_tv', 'theatre'],
    socialLinks: { twitter: 'leoreigns' },
    rankingScore: 980,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: '3',
    userId: '3',
    walletAddress: 'artist_wallet_3',
    username: 'Pixelated',
    role: 'artist',
    bio: 'Digital artist & creator painting with pixels and light. My canvas is the screen, my inspiration is the universe. NFT collections available.',
    profilePhotoUrl: 'https://picsum.photos/seed/102/200/200',
    bannerPhotoUrl: 'https://picsum.photos/seed/202/1200/400',
    location: 'The Grid',
    talentCategory: 'creator',
    talentSubcategories: ['digital_art'],
    socialLinks: { instagram: 'pixelated' },
    rankingScore: 1500,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: '4',
    userId: '4',
    walletAddress: 'business_wallet_1',
    username: 'StarlightEnt',
    role: 'business',
    bio: 'Starlight Entertainment: We find the stars of tomorrow. A full-service production house and talent agency looking for the next big thing.',
    profilePhotoUrl: 'https://picsum.photos/seed/104/200/200',
    bannerPhotoUrl: 'https://picsum.photos/seed/204/1200/400',
    location: 'Metropolis',
    socialLinks: { website: 'starlight.ent' },
    rankingScore: 0,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    id: '5',
    userId: '5',
    walletAddress: 'fan_wallet_1',
    username: 'MusicLover99',
    role: 'fan',
    bio: 'Just here for the vibes and to discover amazing new artists!',
    rankingScore: 0,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  }
];

export const videos: Video[] = [
  {
    id: 'v1',
    videoId: 'v1',
    artistId: '1',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    rawVideoInput: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Check out my new original song "Cosmic Dust"!',
    category: 'music',
    topCount: 150,
    flopCount: 5,
    views: 2500,
    bookCount: 2,
    adoptCount: 1,
    rankingScore: 145,
    bookmarks: 20,
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
  },
  {
    id: 'v2',
    videoId: 'v2',
    artistId: '2',
    videoUrl: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    rawVideoInput: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    description: 'My dramatic monologue from "A Midsummer Night\'s Dream". Hope you like it!',
    category: 'acting',
    topCount: 88,
    flopCount: 12,
    views: 1200,
    bookCount: 0,
    adoptCount: 0,
    rankingScore: 76,
    bookmarks: 10,
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: 'v3',
    videoId: 'v3',
    artistId: '3',
    videoUrl: 'https://www.youtube.com/shorts/3h_nB0sR_RI',
    rawVideoInput: 'https://www.youtube.com/shorts/3h_nB0sR_RI',
    description: 'Speedpaint of my latest digital artwork "Neon City".',
    category: 'creator',
    topCount: 300,
    flopCount: 2,
    views: 5000,
    bookCount: 5,
    adoptCount: 3,
    rankingScore: 298,
    bookmarks: 50,
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: 'v4',
    videoId: 'v4',
    artistId: '1',
    videoUrl: 'https://www.youtube.com/shorts/FT3s2PmctnU',
    rawVideoInput: 'https://www.youtube.com/shorts/FT3s2PmctnU',
    description: 'Acoustic cover of a classic. Let me know what you think!',
    category: 'music',
    topCount: 210,
    flopCount: 8,
    views: 3500,
    bookCount: 1,
    adoptCount: 0,
    rankingScore: 202,
    bookmarks: 35,
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  }
];

export const bookmarks: Bookmark[] = [];
export const tips: Tip[] = [];
